#pragma once

#include "stdint.h"
#include "stdbool.h"

typedef enum
{
  ROTARY_ENCODER_STATUS_OK                                = 0,
  ROTARY_ENCODER_STATUS_WAITING_ENCODER_SENSOR_DATA_OK    = 1,
  ROTARY_ENCODER_STATUS_WAITING_ENCODER_SENSOR_DATA_ERROR = 2,
  ROTARY_ENCODER_STATUS_PARSE_ENCODER_SENSOR_DATA_OK      = 3,
  ROTARY_ENCODER_STATUS_PARSE_ENCODER_SENSOR_DATA_ERROR   = 4,
  ROTARY_ENCODER_STATUS_SEND_DATA_TO_MOTOR_THREAD_OK      = 5,
  ROTARY_ENCODER_STATUS_SEND_DATA_TO_MOTOR_THREAD_ERROR   = 6,
  ROTARY_ENCODER_STATUS_ERROR                             = 0xFF,
}ROTARY_ENCODER_STATUS_t;

typedef enum
{
  ROTARY_ENCODER_STATE_IDLE                        = 0,
  ROTARY_ENCODER_STATE_INIT                        = 1,
  ROTARY_ENCODER_STATE_WAITING_ENCODER_SENSOR_DATA = 2,
  ROTARY_ENCODER_STATE_PARSE_ENCODER_SENSOR_DATA   = 3,
  ROTARY_ENCODER_STATE_SEND_DATA_TO_MOTOR_THREAD   = 4,  
  ROTARY_ENCODER_STATE_DEFAULT                     = 0xFE,
  ROTARY_ENCODER_STATE_ERROR                       = 0xFF
}ROTARY_ENCODER_STATE_t;

typedef struct
{
  ROTARY_ENCODER_STATE_t Previous;
  ROTARY_ENCODER_STATE_t Current;
  ROTARY_ENCODER_STATE_t Next;
}ROTARY_ENCODER_STATE_MASHINE_t;

typedef struct
{
  ROTARY_ENCODER_STATUS_t Status;
  bool Flag_Complete_Encoder_Process;
  ROTARY_ENCODER_STATE_MASHINE_t STATE_MASHINE;
}ROTARY_ENCODER_t;
