#pragma once

#include "stdint.h"
#include "stdbool.h"

typedef enum
{
  ROTARY_ENCODER_STATUS_OK = 0,
  ROTARY_ENCODER_STATUS_ERROR = 0xFF,
}ROTARY_ENCODER_STATUS_t;

typedef enum
{
  ROTARY_ENCODER_STATE_IDLE = 0,
  ROTARY_ENCODER_STATE_INIT = 1,
  ROTARY_ENCODER_STATE_DEFAULT = 0xFE,
  ROTARY_ENCODER_STATE_ERROR = 0xFF
}ROTARY_ENCODER_STATE_t;

typedef struct
{
  ROTARY_ENCODER_STATE_t Previous;
  ROTARY_ENCODER_STATE_t Current;
  ROTARY_ENCODER_STATE_t Next;
}ROTARY_ENCODER_STATE_MASHINE_t;

typedef struct
{
  ROTARY_ENCODER_STATUS_t Status;
  ROTARY_ENCODER_STATE_MASHINE_t STATE_MASHINE;
}ROTARY_ENCODER_t;
